service: yejunwordTest
frameworkVersion: '3'

plugins:
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-plugin-cloudwatch-dashboard
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-2
  deploymentBucket:
    name: yejunwordTest

functions:
  main:
    handler: lambda.handler
    events:
      - http:
          method: any
          path: /{any+}

custom:
  enable_optimize:
    local: false